# Generated by Django 4.1.5 on 2023-01-31 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('valor', models.IntegerField()),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupoItem', to='zssnapp.grupoitens')),
            ],
        ),
        migrations.CreateModel(
            name='ItensInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.CharField(max_length=10)),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='zssnapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=6, null=True, unique=True)),
                ('infectado', models.BooleanField(default=False, null=True)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('long', models.DecimalField(decimal_places=4, max_digits=7)),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
                ('itens_inventario', models.ManyToManyField(to='zssnapp.itensinventario')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quant_itens_compra', models.IntegerField(null=True)),
                ('quant_itens_venda', models.IntegerField()),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
                ('item_comprado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemComprado', to='zssnapp.item')),
                ('item_vendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemVendido', to='zssnapp.item')),
                ('sobrevivente_comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobreviventeComprador', to='zssnapp.sobrevivente')),
                ('sobrevivente_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobreviventeVendendor', to='zssnapp.sobrevivente')),
            ],
        ),
        migrations.CreateModel(
            name='Infectados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denuncias', models.IntegerField()),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
                ('sobrevivente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infectedSurvival', to='zssnapp.sobrevivente')),
            ],
        ),
    ]
