# Generated by Django 4.1.5 on 2023-01-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapp', '0002_alter_infectados_id_alter_inventario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='quant',
        ),
        migrations.AddField(
            model_name='inventario',
            name='tamanho',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infectados',
            name='denuncias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='quant_itens_a_trocar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='quant_itens_troca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='infectado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
