# Generated by Django 4.1.5 on 2023-01-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapp', '0003_grupoitens_remove_inventario_quant_remove_item_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('valor', models.IntegerField()),
                ('data_do_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupoItem', to='zssnapp.grupoitens'),
        ),
    ]
