# Generated by Django 4.1.5 on 2023-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapp', '0005_alter_mercado_quant_itens_a_trocar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
