# Generated by Django 4.1.5 on 2023-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapp', '0006_sobrevivente_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='token',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
